```{r setup, include=F}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)

library(ComplexHeatmap)
library(pheatmap)

library(eulerr)
library(circlize)
library(writexl)
library(readxl)
library(scales)

library(tidyverse)
```


## DATA AND SETUP
```{r include = F}
tpm <- read_tsv("../data/A549vsPrimary_tpm.txt")

mv <- read_tsv("../data/A549vsPrimary_multivariateDEA.txt")
```

```{r helper functions}
make_top10DAVID <- function(file, title){
  read_xlsx(file, sheet = 1) %>%
    mutate(FDR = as.numeric(FDR)) %>%
    arrange(FDR) %>% 
    filter(!(Term %in% c("protein binding", "signal transduction"))) %>%
    filter(Category != "REACTOME_PATHWAY") %>%
    mutate(Term = paste0(toupper(substr(Term, 1, 1)), substr(Term, 2, nchar(Term)))) %>%
    slice_head(n = 10) %>% mutate(Term = factor(Term, levels = rev(unique(Term)))) %>%

    ggplot(., aes(x = -log10(FDR), y = Term)) +
    geom_col(mapping = aes(fill = `Fold Enrichment`)) +
    geom_point(mapping = aes(size = Count)) +
    scale_fill_viridis_c(option = "viridis") +
    scale_x_continuous(expand = expansion(mult = c(0.005, 0.1)),
                       breaks = breaks_pretty(n = 3)) +
    theme_minimal() +
    theme(aspect.ratio = 3,
          panel.grid.minor = element_blank(),
          axis.ticks.y = element_blank(),
          axis.text = element_text(size = 12, color = "black")) +
    labs(x = expression(-log[10] * "FDR"), y = NULL)

  ggsave(title, h = 4, w = 10, dpi = 600)
  print(paste("Saved", title))
}

myColors <- c("NS" = "grey30", 
              "IL1B" = "#FC4E07", 
              "GC" = "#E7B800", 
              "combo" = "#2E9FDF")

#consistent heatmap function
make_heatmap <- function(matrix, colors,
                         colsplit = c(rep("A549", 4), rep("ALI", 5), rep("HBE", 5)), 
                         width = 5, height = 0.08,
                         showLegend = F, rowTitle = NULL, legendTitle = NULL){
  hm = Heatmap(
    matrix,
    col = colors,
    cluster_rows = F, cluster_columns = F,
    show_row_dend = F, show_column_dend = F,
    show_row_names = F, show_column_names = F,
    column_split = colsplit,
    row_gap = unit(1, "mm"), column_gap = unit(2, "mm"),
    width = ncol(matrix)*unit(width, "mm"), height = nrow(matrix)*unit(height, "mm"),
    show_heatmap_legend = showLegend, name = legendTitle, border = T,
    row_title = rowTitle, column_title = unique(colsplit),
    na_col = "white"
  )
  hm
}
```



## UNGROUPED LRT HEATMAPS
```{r identify LRT-significant genes}
goi <- mv %>% filter(lrt_FDR <= 0.05) %>% pull(Gene)
```

```{r heatmap IL1B response in LRT-significant genes}
mat <- mv %>% 
  filter(Gene %in% goi) %>%
  select(Gene, ALI_IL1B_diff, HBE_IL1B_diff) %>%
  column_to_rownames("Gene") %>%
  as.matrix() %>% { .[hclust(dist(.), method = "ward.D2")$order, ] }

annot <- mat %>%
  as.data.frame() %>%
  rownames_to_column("Gene") %>% 
  select(Gene) %>%
  left_join(select(mv, Gene, ALI_IL1B_FDR, HBE_IL1B_FDR), by = "Gene") %>%
  mutate(ALI_IL1B_FDR = ALI_IL1B_FDR <= 0.05,
         HBE_IL1B_FDR = HBE_IL1B_FDR <= 0.05) %>%
  column_to_rownames("Gene")

col = circlize::colorRamp2(
  c(seq(-4, -0.05, length = 90),
    seq(-0.49, 0.49, length = 20),
    seq(0.5, 4, length = 90)),
  colorRampPalette(c("purple", "plum2", "white", "palegreen2", "darkgreen"))(200))

pdf("il1b coefficient heatmap.pdf", width = 8, height = 10)
Heatmap(mat,
        col = col,
        cluster_rows = T, cluster_columns = F,
        clustering_method_rows = "ward.D2",
        show_row_dend = T, show_column_dend = F,
        show_row_names = F, show_column_names = T,
        width = ncol(mat)*unit(30, "mm"), height = nrow(mat)*unit(0.04, "mm"),
        show_heatmap_legend = T, name = "coefficient", border = T,
        row_dend_width = unit(2, "in"),
        left_annotation = rowAnnotation(
          df = annot,
          col = list(ALI_IL1B_FDR = c(`FALSE` = "#F8766D", `TRUE` = "#00BFC4"),
                     HBE_IL1B_FDR = c(`FALSE` = "#F8766D", `TRUE` = "#00BFC4")))
        )
dev.off()

write_xlsx(rownames_to_column(as.data.frame(mat), "Gene"), "il1b coefficient matrix.xlsx")

rm(mat, col, annot)
```

```{r heatmap GC response in LRT-significant genes}
mat <- mv %>% 
  filter(Gene %in% goi) %>%
  select(Gene, ALI_GC_diff, HBE_GC_diff) %>%
  column_to_rownames("Gene") %>%
  as.matrix() %>% { .[hclust(dist(.), method = "ward.D2")$order, ] }

annot <- mat %>%
  as.data.frame() %>%
  rownames_to_column("Gene") %>% 
  select(Gene) %>%
  left_join(select(mv, Gene, ALI_GC_FDR, HBE_GC_FDR), by = "Gene") %>%
  mutate(ALI_GC_FDR = ALI_GC_FDR <= 0.05,
         HBE_GC_FDR = HBE_GC_FDR <= 0.05) %>%
  column_to_rownames("Gene")

col = circlize::colorRamp2(
  c(seq(-4, -0.05, length = 90),
    seq(-0.49, 0.49, length = 20),
    seq(0.5, 4, length = 90)),
  colorRampPalette(c("purple", "plum2", "white", "palegreen2", "darkgreen"))(200))

pdf("gc coefficient heatmap.pdf", width = 8, height = 10)
Heatmap(mat,
        col = col,
        cluster_rows = T, cluster_columns = F,
        clustering_method_rows = "ward.D2",
        show_row_dend = T, show_column_dend = F,
        show_row_names = F, show_column_names = T,
        width = ncol(mat)*unit(30, "mm"), height = nrow(mat)*unit(0.04, "mm"),
        show_heatmap_legend = T, name = "coefficient", border = T,
        row_dend_width = unit(2, "in"),
        left_annotation = rowAnnotation(
          df = annot,
          col = list(ALI_GC_FDR = c(`FALSE` = "#F8766D", `TRUE` = "#00BFC4"),
                     HBE_GC_FDR = c(`FALSE` = "#F8766D", `TRUE` = "#00BFC4")))
        )
dev.off()

write_xlsx(rownames_to_column(as.data.frame(mat), "Gene"), "gc coefficient matrix.xlsx")

rm(mat, col, annot)
```



## LRT GROUP HEATMAPS
```{r identify IL1B LRT groups}
il1b_type1a <- mv %>%
  filter(
    lrt_FDR <= 0.05,                                  # lrt significance
    (ALI_IL1B_FDR <= 0.05 | HBE_IL1B_FDR <= 0.05),    # at least one wald hit
    if_else(                                          # positive direction
      abs(ALI_IL1B_diff) >= abs(HBE_IL1B_diff),
      ALI_IL1B_diff,
      HBE_IL1B_diff
    ) > 0
  )

il1b_type1b <- mv %>%
  filter(
    lrt_FDR <= 0.05,                                  # lrt significance
    (ALI_IL1B_FDR <= 0.05 | HBE_IL1B_FDR <= 0.05),    # at least one wald hit
    if_else(                                          # negative direction
      abs(ALI_IL1B_diff) >= abs(HBE_IL1B_diff),
      ALI_IL1B_diff,
      HBE_IL1B_diff
    ) < 0
  )

il1b_type2 <- mv %>%
  filter(
    lrt_FDR <= 0.05,                                  # lrt significance
    !(Gene %in% il1b_type1a$Gene),                    # not in other groups
    !(Gene %in% il1b_type1b$Gene)
  )

goi_il1b_type1 = unique(c(pull(il1b_type1a, Gene), pull(il1b_type1b, Gene)))
goi_il1b_type2 = unique(c(pull(il1b_type2, Gene)))

# total = 4766 genes - good
```

```{r heatmap IL1B LRT groups - regression coefficients}
mat_il1b_type1a <- il1b_type1a %>% 
  select(Gene, ALI_IL1B_diff, HBE_IL1B_diff) %>%
  column_to_rownames("Gene") %>%
  as.matrix() %>% 
  { .[hclust(dist(.), method = "ward.D2")$order, ] }

annot_il1b_type1a <- mat_il1b_type1a %>%
  as.data.frame() %>%
  rownames_to_column("Gene") %>% 
  select(Gene) %>%
  left_join(select(il1b_type1a, Gene, ALI_IL1B_FDR, HBE_IL1B_FDR), by = "Gene") %>%
  mutate(ALI_IL1B_FDR = ALI_IL1B_FDR <= 0.05,
         HBE_IL1B_FDR = HBE_IL1B_FDR <= 0.05) %>%
  column_to_rownames("Gene")

mat_il1b_type1b <- il1b_type1b %>% 
  select(Gene, ALI_IL1B_diff, HBE_IL1B_diff) %>%
  column_to_rownames("Gene") %>%
  as.matrix() %>% 
  { .[hclust(dist(.), method = "ward.D2")$order, ] }

annot_il1b_type1b <- mat_il1b_type1b %>%
  as.data.frame() %>%
  rownames_to_column("Gene") %>% 
  select(Gene) %>%
  left_join(select(il1b_type1b, Gene, ALI_IL1B_FDR, HBE_IL1B_FDR), by = "Gene") %>%
  mutate(ALI_IL1B_FDR = ALI_IL1B_FDR <= 0.05,
         HBE_IL1B_FDR = HBE_IL1B_FDR <= 0.05) %>%
  column_to_rownames("Gene")

mat_il1b_type2 <- il1b_type2 %>% 
  select(Gene, ALI_IL1B_diff, HBE_IL1B_diff) %>%
  column_to_rownames("Gene") %>%
  as.matrix() %>% 
  { .[hclust(dist(.), method = "ward.D2")$order, ] }

annot_il1b_type2 <- mat_il1b_type2 %>%
  as.data.frame() %>%
  rownames_to_column("Gene") %>% 
  select(Gene) %>%
  left_join(select(il1b_type2, Gene, ALI_IL1B_FDR, HBE_IL1B_FDR), by = "Gene") %>%
  mutate(ALI_IL1B_FDR = ALI_IL1B_FDR <= 0.05,
         HBE_IL1B_FDR = HBE_IL1B_FDR <= 0.05) %>%
  column_to_rownames("Gene")

col = circlize::colorRamp2(
  c(seq(-4, -0.05, length = 90),
    seq(-0.49, 0.49, length = 20),
    seq(0.5, 4, length = 90)),
  colorRampPalette(c("purple", "plum2", "white", "palegreen2", "darkgreen"))(200))

hm1 <- Heatmap(mat_il1b_type1a,
        col = col,
        cluster_rows = T, cluster_columns = F,
        clustering_method_rows = "ward.D2",
        show_row_dend = F, show_column_dend = F,
        show_row_names = F, show_column_names = T,
        width = ncol(mat_il1b_type1a)*unit(30, "mm"), height = nrow(mat_il1b_type1a)*unit(0.04, "mm"),
        show_heatmap_legend = T, name = NULL, border = T,
        left_annotation = rowAnnotation(
          df = annot_il1b_type1a,
          col = list(ALI_IL1B_FDR = c(`FALSE` = "#F8766D", `TRUE` = "#00BFC4"),
                     HBE_IL1B_FDR = c(`FALSE` = "#F8766D", `TRUE` = "#00BFC4")),
          show_annotation_name = FALSE),
        row_title = "type 1a"
        )

hm2 <- Heatmap(mat_il1b_type1b,
        col = col,
        cluster_rows = T, cluster_columns = F,
        clustering_method_rows = "ward.D2",
        show_row_dend = F, show_column_dend = F,
        show_row_names = F, show_column_names = T,
        width = ncol(mat_il1b_type1b)*unit(30, "mm"), height = nrow(mat_il1b_type1b)*unit(0.04, "mm"),
        show_heatmap_legend = T, name = NULL, border = T,
        left_annotation = rowAnnotation(
          df = annot_il1b_type1b,
          col = list(ALI_IL1B_FDR = c(`FALSE` = "#F8766D", `TRUE` = "#00BFC4"),
                     HBE_IL1B_FDR = c(`FALSE` = "#F8766D", `TRUE` = "#00BFC4"))),
        row_title = "type 1b"
        )

hm3 <- Heatmap(mat_il1b_type2,
        col = col,
        cluster_rows = T, cluster_columns = F,
        clustering_method_rows = "ward.D2",
        show_row_dend = F, show_column_dend = F,
        show_row_names = F, show_column_names = T,
        width = ncol(mat_il1b_type2)*unit(30, "mm"), height = nrow(mat_il1b_type2)*unit(0.04, "mm"),
        show_heatmap_legend = T, name = "coefficient", border = T,
        left_annotation = rowAnnotation(
          df = annot_il1b_type2,
          col = list(ALI_IL1B_FDR = c(`FALSE` = "#F8766D", `TRUE` = "#00BFC4"),
                     HBE_IL1B_FDR = c(`FALSE` = "#F8766D", `TRUE` = "#00BFC4")),
          show_annotation_name = FALSE),
        row_title = "type 2"
        )

pdf("il1b lrt groups heatmap.pdf", width = 8, height = 10)
draw(hm1 %v% hm3 %v% hm2)
dev.off()

write_xlsx(list("type1a" = rownames_to_column(as.data.frame(mat_il1b_type1a), "Gene"), 
                "type2" = rownames_to_column(as.data.frame(mat_il1b_type2), "Gene"), 
                "type1b" = rownames_to_column(as.data.frame(mat_il1b_type1b), "Gene")),
           "il1b lrt groups matrices.xlsx")


rm(list = ls(pattern = "annot"))
rm(list = ls(pattern = "hm"))
rm(list = ls(pattern = "mat_"))
rm(col)
```

```{r heatmap IL1B LRT groups - z-scored expression}
mat <- tpm %>%
  mutate(sample = paste(celltype, treatment, rep)) %>%
  filter(treatment %in% c("IL1B", "combo")) %>%
  select(Gene, sample, log2fold) %>%
  pivot_wider(values_from = "log2fold", names_from = "sample") %>%
  select(Gene, 
         contains("A549 IL1B"), contains("A549 combo"),
         contains("ALI IL1B"), contains("ALI combo"),
         contains("HBE IL1B"), contains("HBE combo"))

# %>%
#   column_to_rownames("Gene") %>%
#   as.matrix() %>%
#   t() %>% scale() %>% t() %>%
#   as.data.frame() %>%
#   rownames_to_column("Gene")

mat_type1a <- mat %>%
  filter(Gene %in% readLines("../data/clustersOfInterest/lrt_IL1B_type1A.txt")) %>%
  column_to_rownames("Gene") %>% as.matrix() %>%
  { .[hclust(dist(.), method = "ward.D2")$order, ] }

mat_type1b <- mat %>%
  filter(Gene %in% readLines("../data/clustersOfInterest/lrt_IL1B_type1B.txt")) %>%
  column_to_rownames("Gene") %>% as.matrix() %>%
  { .[hclust(dist(.), method = "ward.D2")$order, ] }

mat_type2 <- mat %>%
  filter(Gene %in% readLines("../data/clustersOfInterest/lrt_IL1B_type2.txt")) %>%
  column_to_rownames("Gene") %>% as.matrix() %>%
  { .[hclust(dist(.), method = "ward.D2")$order, ] }

column_split = factor(
  c(
    rep("A5_IL", 4),  rep("A5_combo", 4),
    rep("ALI_IL", 5), rep("ALI_combo", 5),
    rep("HBE_IL", 5), rep("HBE_combo", 5)
  ),
  levels = c("A5_IL",  "A5_combo", 
             "ALI_IL", "ALI_combo",
             "HBE_IL", "HBE_combo")
)

col = circlize::colorRamp2(
  seq(-2, 2, length = 200),
  colorRampPalette(c("steelblue4", "steelblue3" , "white", "firebrick3", "firebrick4"))(200)
  )

hm1 = make_heatmap(mat_type1a, col = col, colsplit = column_split, rowTitle = "amplified in primary",
                   height = 0.05)
hm2 = make_heatmap(mat_type2,  col = col, colsplit = column_split, rowTitle = "complex interaction",
                   height = 0.05, showLegend = TRUE, legendTitle = "log2fold tpm")
hm3 = make_heatmap(mat_type1b, col = col, colsplit = column_split, rowTitle = "dampened in primary",
                   height = 0.05)

pdf("IL1B lrt groups expression heatmap.pdf", width = 8, height = 10)
draw(hm1 %v% hm2 %v% hm3)
dev.off()
```



```{r identify GC LRT groups}
gc_type1a <- mv %>%
  filter(
    lrt_FDR <= 0.05,                                  # lrt significance
    (ALI_GC_FDR <= 0.05 | HBE_GC_FDR <= 0.05),        # at least one wald hit
    if_else(                                          # positive direction
      abs(ALI_GC_diff) >= abs(HBE_GC_diff),
      ALI_GC_diff,
      HBE_GC_diff
    ) > 0
  )

gc_type1b <- mv %>%
  filter(
    lrt_FDR <= 0.05,                                  # lrt significance
    (ALI_GC_FDR <= 0.05 | HBE_GC_FDR <= 0.05),        # at least one wald hit
    if_else(                                          # negative direction
      abs(ALI_GC_diff) >= abs(HBE_GC_diff),
      ALI_GC_diff,
      HBE_GC_diff
    ) < 0
  )

gc_type2 <- mv %>%
  filter(
    lrt_FDR <= 0.05,                                  # lrt significance
    !(Gene %in% gc_type1a$Gene),                      # not in other groups
    !(Gene %in% gc_type1b$Gene)
  )

# total = 4766 genes - good
```

```{r heatmap GC LRT groups}
mat_gc_type1a <- gc_type1a %>% 
  select(Gene, ALI_GC_diff, HBE_GC_diff) %>%
  column_to_rownames("Gene") %>%
  as.matrix() %>% 
  { .[hclust(dist(.), method = "ward.D2")$order, ] }

annot_gc_type1a <- mat_gc_type1a %>%
  as.data.frame() %>%
  rownames_to_column("Gene") %>% 
  select(Gene) %>%
  left_join(select(gc_type1a, Gene, ALI_GC_FDR, HBE_GC_FDR), by = "Gene") %>%
  mutate(ALI_GC_FDR = ALI_GC_FDR <= 0.05,
         HBE_GC_FDR = HBE_GC_FDR <= 0.05) %>%
  column_to_rownames("Gene")

mat_gc_type1b <- gc_type1b %>% 
  select(Gene, ALI_GC_diff, HBE_GC_diff) %>%
  column_to_rownames("Gene") %>%
  as.matrix() %>% 
  { .[hclust(dist(.), method = "ward.D2")$order, ] }

annot_gc_type1b <- mat_gc_type1b %>%
  as.data.frame() %>%
  rownames_to_column("Gene") %>% 
  select(Gene) %>%
  left_join(select(gc_type1b, Gene, ALI_GC_FDR, HBE_GC_FDR), by = "Gene") %>%
  mutate(ALI_GC_FDR = ALI_GC_FDR <= 0.05,
         HBE_GC_FDR = HBE_GC_FDR <= 0.05) %>%
  column_to_rownames("Gene")

mat_gc_type2 <- gc_type2 %>% 
  select(Gene, ALI_GC_diff, HBE_GC_diff) %>%
  column_to_rownames("Gene") %>%
  as.matrix() %>% 
  { .[hclust(dist(.), method = "ward.D2")$order, ] }

annot_gc_type2 <- mat_gc_type2 %>%
  as.data.frame() %>%
  rownames_to_column("Gene") %>% 
  select(Gene) %>%
  left_join(select(gc_type2, Gene, ALI_GC_FDR, HBE_GC_FDR), by = "Gene") %>%
  mutate(ALI_GC_FDR = ALI_GC_FDR <= 0.05,
         HBE_GC_FDR = HBE_GC_FDR <= 0.05) %>%
  column_to_rownames("Gene")

col = circlize::colorRamp2(
  c(seq(-4, -0.05, length = 90),
    seq(-0.49, 0.49, length = 20),
    seq(0.5, 4, length = 90)),
  colorRampPalette(c("purple", "plum2", "white", "palegreen2", "darkgreen"))(200))

hm1 <- Heatmap(mat_gc_type1a,
        col = col,
        cluster_rows = T, cluster_columns = F,
        clustering_method_rows = "ward.D2",
        show_row_dend = F, show_column_dend = F,
        show_row_names = F, show_column_names = T,
        width = ncol(mat_gc_type1a)*unit(30, "mm"), height = nrow(mat_gc_type1a)*unit(0.04, "mm"),
        show_heatmap_legend = T, name = NULL, border = T,
        left_annotation = rowAnnotation(
          df = annot_gc_type1a,
          col = list(ALI_GC_FDR = c(`FALSE` = "#F8766D", `TRUE` = "#00BFC4"),
                     HBE_GC_FDR = c(`FALSE` = "#F8766D", `TRUE` = "#00BFC4")),
          show_annotation_name = FALSE),
        row_title = "type 1a"
        )

hm2 <- Heatmap(mat_gc_type1b,
        col = col,
        cluster_rows = T, cluster_columns = F,
        clustering_method_rows = "ward.D2",
        show_row_dend = F, show_column_dend = F,
        show_row_names = F, show_column_names = T,
        width = ncol(mat_gc_type1b)*unit(30, "mm"), height = nrow(mat_gc_type1b)*unit(0.04, "mm"),
        show_heatmap_legend = T, name = NULL, border = T,
        left_annotation = rowAnnotation(
          df = annot_gc_type1b,
          col = list(ALI_GC_FDR = c(`FALSE` = "#F8766D", `TRUE` = "#00BFC4"),
                     HBE_GC_FDR = c(`FALSE` = "#F8766D", `TRUE` = "#00BFC4"))),
        row_title = "type 1b"
        )

hm3 <- Heatmap(mat_gc_type2,
        col = col,
        cluster_rows = T, cluster_columns = F,
        clustering_method_rows = "ward.D2",
        show_row_dend = F, show_column_dend = F,
        show_row_names = F, show_column_names = T,
        width = ncol(mat_gc_type2)*unit(30, "mm"), height = nrow(mat_gc_type2)*unit(0.04, "mm"),
        show_heatmap_legend = T, name = "coefficient", border = T,
        left_annotation = rowAnnotation(
          df = annot_gc_type2,
          col = list(ALI_GC_FDR = c(`FALSE` = "#F8766D", `TRUE` = "#00BFC4"),
                     HBE_GC_FDR = c(`FALSE` = "#F8766D", `TRUE` = "#00BFC4")),
          show_annotation_name = FALSE),
        row_title = "type 2"
        )

pdf("gc lrt groups heatmap.pdf", width = 8, height = 10)
draw(hm1 %v% hm3 %v% hm2)
dev.off()

write_xlsx(list("type1a" = rownames_to_column(as.data.frame(mat_gc_type1a), "Gene"), 
                "type2" = rownames_to_column(as.data.frame(mat_gc_type2), "Gene"), 
                "type1b" = rownames_to_column(as.data.frame(mat_gc_type1b), "Gene")),
           "gc lrt groups matrices.xlsx")


rm(list = ls(pattern = "annot"))
rm(list = ls(pattern = "hm"))
rm(list = ls(pattern = "mat_"))
rm(col)
```

```{r profile LRT groups}
make_top10DAVID("../data/clustersOfInterest/DAVIDChartReport_lrt_IL1B_type1A_2025-12-23.xlsx",
                "lrt_IL1B_type1A.jpg")

make_top10DAVID("../data/clustersOfInterest/DAVIDChartReport_lrt_IL1B_type1B_2025-12-23.xlsx",
                "lrt_IL1B_type1B.jpg")

make_top10DAVID("../data/clustersOfInterest/DAVIDChartReport_lrt_IL1B_type2_2025-12-23.xlsx",
                "lrt_IL1B_type2.jpg")
```

```{r cleanup}
rm(list = ls(pattern = "^gc_type"))
rm(list = ls(pattern = "^il1b_type"))
```



## LRT GROUPS (MULTIVARIATE) VS VENN GROUPS (UNIVARIATE)
```{r pull venn groups}
goi_il1b_venn <- c()
for(f in list.files("../data/genelists/")){
  if (str_detect(f, "IL1B")){
    goi_il1b_venn <- sort(unique(c(goi_il1b_venn, readLines(paste0("../data/genelists/", f)))))
    rm(f)
  }
}

goi_il1b_looksConserved <- readLines("../data/clustersOfInterest/venn_looksConserved.txt")
goi_il1b_A549only <- readLines("../data/clustersOfInterest/venn_A549_only.txt")
goi_il1b_primaryOnly <- readLines("../data/clustersOfInterest/venn_primaryOnly.txt")
```

```{r visualize sets}
groups_il1b = sort(unique(c(goi_il1b_type1, goi_il1b_type2, goi_il1b_venn))) %>%
  as.data.frame(nm = "Gene") %>%
  group_by(Gene) %>%
  mutate(
    type0 = if_else(Gene %in% goi_il1b_venn, "type 0", NA),
    type1 = if_else(Gene %in% goi_il1b_type1, "type 1", NA),
    type2 = if_else(Gene %in% goi_il1b_type2, "type 2", NA),
    lc    = if_else(Gene %in% goi_il1b_looksConserved, "lc", NA),
    a5    = if_else(Gene %in% goi_il1b_A549only, "a5", NA),
    pr    = if_else(Gene %in% goi_il1b_primaryOnly, "pr", NA)
  ) 

set.seed(777)
venn_il1b <- groups_il1b %>%
  mutate(group = paste(na.omit(c(type0, type1, type2)), collapse = "&")) %>%
  ungroup() %>% select(Gene, group) %>% count(group) %>%
  deframe() %>% euler(shape = "ellipse")
set.seed(777)
venn_il1b_lc <- groups_il1b %>%
  mutate(group = paste(na.omit(c(type0, type1, type2, lc)), collapse = "&")) %>%
  ungroup() %>% select(Gene, group) %>% count(group) %>%
  deframe() %>% euler(shape = "circle")
set.seed(777)
venn_il1b_a5 <- groups_il1b %>%
  mutate(group = paste(na.omit(c(type0, type1, type2, a5)), collapse = "&")) %>%
  ungroup() %>% select(Gene, group) %>% count(group) %>%
  deframe() %>% euler(shape = "circle")
set.seed(777)
venn_il1b_pr <- groups_il1b %>%
  mutate(group = paste(na.omit(c(type0, type1, type2, pr)), collapse = "&")) %>%
  ungroup() %>% select(Gene, group) %>% count(group) %>%
  deframe() %>% euler(shape = "circle")

png("geneClasses (type 0 vs 1 vs 2) venn.png", width=720, height=480, res = 100)
plot(venn_il1b, quantities = list(type = c("counts")), main = "IL1B-regulated genes")
dev.off()

png("geneClasses venn with lc.png", width=720, height=480, res = 100)
plot(venn_il1b_lc, quantities = list(type = c("counts")), main = "IL1B-regulated genes")
dev.off()

png("geneClasses venn with a5.png", width=720, height=480, res = 100)
plot(venn_il1b_a5, quantities = list(type = c("counts")), main = "IL1B-regulated genes")
dev.off()

png("geneClasses venn with pr.png", width=720, height=480, res = 100)
plot(venn_il1b_pr, quantities = list(type = c("counts")), main = "IL1B-regulated genes")
dev.off()






%>%
  mutate(group = paste(na.omit(c(type0, type1, type2, lc)), collapse = "&")) %>%
  ungroup() %>%
  select(Gene, group) %>%
  count(group) %>%
  deframe() %>%
  euler(shape = "ellipse")
```

```{r cleanup}
rm(list = ls(pattern = "^venn_"))
rm(list = ls(pattern = "^goi_"))
rm(list = ls(pattern = "^groups_"))
```



## RELATIVE CONTRIBUTIONS EACH TREATMENT TO LRT DIVERGENCE
```{r violinboxplots and descriptive stats}
prop_divergence <- mv %>%
  select(Gene, contains("diff")) %>%
  group_by(Gene) %>%
  mutate(IL1B_divergence  = var(c(0, ALI_IL1B_diff,  HBE_IL1B_diff)),
         GC_divergence    = var(c(0, ALI_GC_diff,    HBE_GC_diff)),
         combo_divergence = var(c(0, ALI_combo_diff, HBE_combo_diff))) %>%
  ungroup() %>%
  mutate(
    total_divergence = IL1B_divergence + GC_divergence + combo_divergence,
    prop_IL1B  = IL1B_divergence  / total_divergence,
    prop_GC    = GC_divergence    / total_divergence,
    prop_combo = combo_divergence / total_divergence
  ) %>%
  select(-contains("diff"), -contains("divergence")) %>%
  pivot_longer(cols = contains("prop"), names_to = "driver", values_to = "proportion") %>%
  mutate(driver = gsub("prop_", "", driver),
         driver = factor(driver, levels = unique(driver))) %>%
  mutate("IL1B response" = case_when(
    Gene %in% readLines("../data/clustersOfInterest/lrt_IL1B_type1A.txt") ~ "amplified in primary",
    Gene %in% readLines("../data/clustersOfInterest/lrt_IL1B_type1B.txt") ~ "dampened in primary",
    Gene %in% readLines("../data/clustersOfInterest/lrt_IL1B_type2.txt") ~ "complex interaction"
  )) %>%
  mutate("GC response" = case_when(
    Gene %in% readLines("../data/clustersOfInterest/lrt_GC_type1A.txt") ~ "amplified in primary",
    Gene %in% readLines("../data/clustersOfInterest/lrt_GC_type1B.txt") ~ "dampened in primary",
    Gene %in% readLines("../data/clustersOfInterest/lrt_GC_type2.txt") ~ "complex interaction"
  )) %>%
  na.omit() %>%
  pivot_longer(cols = c("IL1B response", "GC response"), names_to = "lrt_group", values_to = "type") %>%
  mutate(lrt_group = factor(lrt_group, levels = c("IL1B response", "GC response"))) %>%
  select(Gene, lrt_group, type, driver, proportion) %>%
  arrange(Gene, lrt_group, type, driver)

ggplot(prop_divergence, aes(x = driver, y = 100 * proportion, fill = driver)) +
  facet_grid(type~lrt_group) +
  geom_violin(scale = "width", lwd = 0.3, color = "black") +
  geom_boxplot(outliers = F, width = 0.2, lwd = 0.3, color = "black") +
  theme_bw() +
  theme(aspect.ratio = 1.3333,
        strip.background = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "none",
        plot.title = element_text(size = 8),
        axis.title = element_text(size = 9)) +
  labs(x = NULL, y = "% divergence explained") +
  scale_fill_manual(values = myColors) +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.15)),
                     breaks = c(0, 25, 50, 75, 100))

ggsave("prop divergence by lrt group.png", h = 5, w = 3, dpi = 600)

ggplot(prop_divergence, aes(x = driver, y = 100 * proportion, fill = driver)) +
  geom_violin(scale = "width", lwd = 0.3, color = "black") +
  geom_boxplot(outliers = F, width = 0.2, lwd = 0.3, color = "black") +
  theme_bw() +
  theme(aspect.ratio = 1,
        axis.ticks.x = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "none",
        axis.title = element_text(size = 9)) +
  labs(x = NULL, y = "% divergence explained") +
  scale_fill_manual(values = myColors) +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.15)),
                     breaks = c(0, 25, 50, 75, 100))

ggsave("prop divergence.png", h = 2, w = 2, dpi = 600)

# Because each distribution contains hundreds to thousands of genes, classical hypothesis tests are heavily overpowered and detect trivial differences. We will therefore focus on effect sizes and distributional patterns rather than adjusted p-values.

rm(list = ls(pattern = "prop_divergence"))
```



